https://earthly.dev/blog/python-makefile/

VENV = pytest_venv
PYTHON = $(VENV)/bin/python3
PIP = $(VENV)/bin/pip

hello:
	echo "Hello, World"
	echo "This line will print if the file hello does not exist."

run:
	"/home/richa-mishra/Desktop/Python Programming/.venv/bin/python" "/home/richa-mishra/Desktop/Python Programming/pytest_programming/wallet.py"

clean:
    rm -rf __pycache__
	 rm -rf $(VENV)

setup: requirement.txt
	pip install -r requirements.txt

venv/bin/activate: requirements.txt
 python3 -m venv $(VENV)
 ./$(VENV)/bin/pip install -r requirements.txt

 run: $(VENV)/bin/activate
 ./$(VENV)/bin/python3 app.py


help: ## Display this help message.
    @echo "Please use \`make <target>' where <target> is one of"
    @awk -F ':.*?## ' '/^[a-zA-Z]/ && NF==2 {printf "\033[36m  %-28s\033[0m %s\n", $$1, $$2}' Makefile | sort

requirements: ## install development environment requirements
    pip install -r requirements.txt

upgrade: export CUSTOM_COMPILE_COMMAND=make upgrade
upgrade: ## Upgrade requirements with pip-tools.
    pip install -qr requirements/pip-tools.txt
    pip-compile --upgrade -o requirements/pip-tools.txt requirements/pip-tools.in
    pip-compile --upgrade -o requirements/base.txt requirements/base.in
    pip-compile --upgrade -o requirements/doc.txt requirements/doc.in
    pip-compile --upgrade -o requirements/dev.txt requirements/dev.in

selfcheck: ## Check that the Makefile is free of Make syntax errors.

activate:
    bash -c "venv/bin/activate"

################################################
#pip install inside virtualenv:

# Makefile

all: install run

install: venv
    : # Activate venv and install smthing inside
    . venv/bin/activate && pip install -r requirements.txt
    : # Other commands here

venv:
    : # Create venv if it doesn't exist
    : # test -d venv || virtualenv -p python3 --no-site-packages venv
    test -d venv || python3 -m venv venv

run:
    : # Run your app here, e.g
    : # determine if we are in venv,
    : # see https://stackoverflow.com/q/1871549
    . venv/bin/activate && pip -V

    : # Or see @wizurd's answer to exec multiple commands
    . venv/bin/activate && (\
      python3 -c 'import sys; print(sys.prefix)'; \
      pip3 -V \
    )

clean:
    rm -rf venv
    find -iname "*.pyc" -delete

############################################################
############################################################